# config/meta.yml
meta_product_name: "Frometon"
meta_title: "Frometon - ton nouveau compagnon fromage, agit comme un assistant personnel sur les sujets fromage ! L'application te permet de trouver le produit qui te correspond. Complète ton profil avec ton goût pour chaque type de fromage, ou personnalise directement ta recherche sur la homepage : frometon se charge du reste !"
meta_description: "Frometon est ton assistant personnel, côté fromage ! L'application te permet de trouver le produit qui te correspond. Complète ton profil avec ton goût pour chaque type de fromage, ou personnalise directement ta recherche sur la homepage : frometon se charge du reste !"
meta_image: "frometon_cover.png" # should exist in `app/assets/images/`
# app/assets/images/frometon_cover.jpeg
